### ISSUE TITLE
some packaging tool/packager/tag docs missing

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3757]
This was mentioned in Discord channel, no link to topic.  Comments are relevant as of 4.0.1 release.

- [ ] Three Tool specs that are used by packaging (beyond `packaging` itself) have no documentation files / no `<tool name=...>`: `ipkg.py`, `wix.py`, `rpm.py`.  These are not used by the user directly, so maybe that's intentional?   If the user selects packaging in their tool list, and a relevant package type, those will have their `generate` method called.  The other packagers use the `tar` and `zip` tools, but those do have documentation, and do make some sense to call independently of the packaging setup so they're not a problem.
- [ ] All of the packagers have some tags which are required, the man page says so, but there's no way to tell what they are without examining the source of the packager in `SCons/Tool/packaging/*`.  
- [ ] There is a `Tag` builder created by the packaging tool.  It's just a plain function, but it does register in your environment's `BUILDER` list, should it be documented as a builder?  It is not the same as the `Tag` function, but calls it.
- [x] The `--packge-type` cmdline option does not appear in the manpage.  [addressed in #3756]
- [x] Manpage claims you can list the currently supported packagers by using `--help`, but this is not true [addressed in #3756 by removing the claim]
- [ ] Existing text for Package builder claims: "The packaging information is specified with the help of construction variables documented below." [this claim is removed in #3756]. Unfortunately, the "below" is true only if you look in the source doc file (`SCons/Tool/packaging/packaging.xml`): the doc build distributes consvars to completely different places in the doc from the builder, so there is actually no list of constructions vars associated with `Package`.  Tools can have "uses" and "sets" lists, but the packaging tool isn't the right place for those lists, and the individual packagers aren't tools - they are instead modules imported on the fly by the packaging tool, and their externally callable interface is a `package` function, not `exists` and `generate` as for a tool, so we can't add the list to docs for the packagers. And since packagers don't fit in any of the four defined categories (Tool, Builder, Function, Variable) there actually aren't any docs to add them to!
- [ ] The tags used to control packaging are described as construction variables in the doc, but they aren't really.  They are not used in the context of a consenv (although the msi packager uses the env as a temporary stash to pass them between parts of that file, but that's not really a true construction var IMO). Do we need a different doc category for tags?
- [ ] Do we in fact need a separate manpage section on Packaging to make it possible to document/find this stuff? Or isn't it really important enough to bother with?
